---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: nonprod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
<<<<<<< HEAD
          image: pushpendrasingh3tcscom/test-app:1.3.1
=======
          image: pushpendrasingh3tcscom/test-app:1.3.0
>>>>>>> 5a8461077fa6d11438da3158e366cf07bb8039e4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache
  namespace: nonprod-app
  labels:
    app: apache
spec:
  type: NodePort      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
