---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: prod-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: pushpendrasingh3tcscom/test-app:1.3.6
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache
  namespace: prod-app
  labels:
    app: apache
spec:
  type: NodePort      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
