---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-manual-app
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: manual-approval-project
  source:
    repoURL: https://github.com/pushpendrasingh3/manual-approval.git
    targetRevision: developer
    path: argocd-config/prod
  destination:
    server: https://34.47.151.239
    namespace: prod-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
