---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-manual-app
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: manual-approval-project
  source:
    repoURL: https://github.com/pushpendrasingh3/manual-approval.git
    targetRevision: developer
    path: argocd-config/dev
  destination:
<<<<<<< HEAD:argocd-config/application_dev.yaml
    server: https://34.47.198.97
    namespace: nonprod-app
=======
    server: https://35.244.61.26
    namespace: test-app
>>>>>>> 5a8461077fa6d11438da3158e366cf07bb8039e4:argocd-config/application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
