apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-test-app-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Working with CI-CD Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: test-app
    server: https://35.244.61.26

  - namespace: test-app
    server: https://35.244.55.196  

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

