---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-gke-my-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod-gke-my-app-project
  source:
    repoURL: https://github.com/pushpendrasingh3/manual-approval.git
    targetRevision: main
    path: argocd-config/prod
    #path: environments/prod/my-app
  destination:
    server: https://35.244.55.196
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
