---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-my-test-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster2-my-test-app-project
  source:
    repoURL: https://github.com/pushpendrasingh3/manual-approval.git
    targetRevision: developer
    path: argocd-config/dev
    #path: environments/dev/my-app
  destination:
    server: https://34.131.169.30
    namespace: test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
