name: Deploy to Kubernetes

on:
  push:
    branches: [developer]
  #pull_request:
    #branches: [developer]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_USER:     ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GH_TOKEN:        ${{ secrets.GH_TOEKN }}  
  GIT_TAG: 1.3.4
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        run: |
          echo "GIT_TAG=`cat version`" >> "$GITHUB_ENV"
          echo "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          # echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> "$GITHUB_ENV"
          #echo "GIT_TAG=`cat version`" >> "$GITHUB_ENV"
          echo "$GITHUB_ENV"
          docker build -t ${DOCKER_USER}/test-app:${GIT_TAG} -f argocd-config/Dockerfile .
          docker push ${DOCKER_USER}/test-app:${GIT_TAG}
      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: pushpendrasingh3/manual-approval
          ref: 'developer'
          token: ${{ secrets.GH_TOKEN }}        
