name: main
on:
  pull_request:
    branches: [main]      
  workflow_dispatch:
    branches: [main]  
env:
  INPUT_SECRET: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_TOKEN }}
          approvers: pushpendrasingh3
   
      - name: Deploy to production
        run: echo deploying

      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: pushpendrasingh3/manual-approval
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}
