# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  [push,workflow_dispatch]
  #push:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#environment: "Production"
env:
  environment: "Production"
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying
        run: echo deploying

  release:
    name: production-push
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${ GH_TOKEN }
          approvers: pushpendrasingh3
          minimum-approvals: 1
          issue-title: "code Push to production from dev"
          issue-body: "Please approve/deny version:1.0.0"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
          
      - name: Push to production
        run: echo deploying
