name: Manually Rollback
on:
   workflow_dispatch:
     inputs:
       revision:
         description: 'The revision to rollback to'
         required: true

       branch:
         description: 'The branch that the rollback affects'
         required: true

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Rolls back to certain version
        uses: fivebluepetals/rollback-action@v1.0
        with:
          branch: ${{ github.event.inputs.branch }}
          revision: ${{ github.events.inputs.revision }}    
