# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  [push,workflow_dispatch]
  #push:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#environment: "Production"
env:
  environment: "Production"
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ENV_LEVEL: ${{ vars.ENV_LEVEL }}
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "building"
          echo "GH_TOKEN = ${GH_TOKEN} "
          echo "ENV_LEVEL = ${ENV_LEVEL} "
          echo "GITHUB_ENV = ${GITHUB_ENV} "
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying
        run: echo deploying
